version: 2
jobs:
  tests_and_build:
    docker:
    - image: docker:17.09.0-ce
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Configure env
        command: echo $(date +%Y%V) > ~/.cache-date.txt
    - restore_cache:
        keys:
        - v1-{{ checksum "requirements.txt" }}-{{ checksum "~/.cache-date.txt" }}
        paths:
        - /caches/venueserver.tar

    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/venueserver.tar | true

    - run:
        name: Build application Docker image
        command: |
          docker build --cache-from=venueserver -t venueserver .

    - run:
        name: Install docker-compose
        command: |
          apk add --no-cache \
            py-pip
          pip install \
            docker-compose==1.22.0

    - run:
        name: Run tests
        command: |
          docker-compose -f docker-compose-tests.yml up -d
          docker-compose -f docker-compose-tests.yml exec web pytest

    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p /caches
          docker save -o /caches/venueserver.tar venueserver

    - save_cache:
        name: Save cache to the circle CI
        key: v1-{{ checksum "requirements.txt" }}-{{ checksum "~/.cache-date.txt" }}
        paths:
        - /caches/venueserver.tar

    - run:
        name: Tag image and push to server
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
              TAG=v0.1.$CIRCLE_BUILD_NUM
              docker build --cache-from=venueserver -t volentixlabs/venueserver:$TAG .
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
              docker push volentixlabs/venueserver:$TAG
          else
            echo 'Skip current step for this branch'
          fi

  deploy:
    docker:
    - image: volentixlabs/aws-kube-deploy:v0.1.2
    working_directory: ~/repo
    steps:
    - checkout
    - run: kops export kubecfg
    - run: |
        TAG=v0.1.$CIRCLE_PREVIOUS_BUILD_NUM
        sed 's/IMAGE_VERSION/'$TAG'/' kube/dev.yml.template > kube/dev.yml
        kubectl apply -f kube/dev.yml

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - tests_and_build
    - deploy:
        requires:
        - tests_and_build
        filters:
          branches:
            only: master
